### ISSUE TITLE
I couldn't make it work

### ISSUE THREAD

**Issue by trautSS** [patrikzudel/PatrikZeros-CSGO-Sound-Fix#1]
I downloaded the .zip, extracted it and ran the .exe but nothing happened in game but the icon appeared in the tray.

I'd be thankful if anybody can help

**Comment by patrikzudel** [comment]
**Important**
Put "gamestate_integration_VolumeFix.cfg" into your "Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg"

**Comment by trautSS** [comment]
> **Important** Put "gamestate_integration_VolumeFix.cfg" into your "Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg"

I'm sorry, that's why I closed the issue, but thanks!

**Comment by trautSS** [comment]
> **Important** Put "gamestate_integration_VolumeFix.cfg" into your "Steam\steamapps\common\Counter-Strike Global Offensive\csgo

I'm sorry, that's why i closed the issue, but thanks!
