### ISSUE TITLE
pycaw has a dependency of enum34 which pyinstaller reject

### ISSUE THREAD

**Issue by coralsundy** [patrikzudel/PatrikZeros-CSGO-Sound-Fix#2]
```
The 'enum34' package is an obsolete backport of a standard library package and is incompatible with PyInstaller
```

@patrikzudel what version of python you are using?
I am on windows with 3.7 and use pywin32 to install pycaw/pyinstaller since pyinstaller cannot cross-compile.

I made some changes so my max volume is 0.2 while low volume is 0.0 but stuck due to this package enum34 not accepted by Pyinstaller.

Can you let me know your python version and other dependencies?
Are you using Python <3.4 for this?

Thanks.

**Comment by coralsundy** [comment]
Seems like the author fixed this on the code of pycaw, but not seeing it on pypi:
https://github.com/AndreMiras/pycaw/releases/tag/v20190904
https://pypi.org/project/pycaw/20181226/

Need some update on the readme so people install through developer branch:
pip install https://github.com/AndreMiras/pycaw/archive/develop.zip

Thanks.

**Comment by patrikzudel** [comment]
I've used `pip uninstall enum` and compiled it to .exe
After that you can reinstall enum, there of course are better solutions and I will probably fix that in the future.

**Comment by coralsundy** [comment]
> I've used `pip uninstall enum34` and compiled it to .exe After that you can reinstall enum34, there of course are better solutions and I will probably fix that in the future.

Yeah that is what I figure out as well.

There is some issue with the current implementation tho.
I am not very familiar with gamestate, but from what I have tested there are these kind of situations where it does not apply
* There is a delay between you get flashed and already hear the 1st few ms of the sound before it turns off, so technically you still hear the sound then suddenly cutoff.
* The resume is very fast if you only get partial blind, result in the high pitch sound quickly cut off and resume, if there is some sort of delay to set it would be better.
* If the flash pop behind you or right next to your butt, there is little to none cut off, probably a mere 100ms which doesnt really help

Overall, this is a good start I think, especially helpful to me who has an old sound card and equilizer APO does not run on it.

Thanks.

**Comment by patrikzudel** [comment]
Sadly 1, and 3, is the limitation of game state integration, it doesn't give information about getting flashed at all when it pops behind you. For 2, I will do some testing and I'll see what I can do.
I might be able to lower the delay with playing around with the settings in the .cfg file but I think it might reduce performance. I'll look into it.
