### ISSUE TITLE
[BUG] Tray icon stuck sometimes after exit csgo

### ISSUE THREAD

**Issue by coralsundy** [patrikzudel/PatrikZeros-CSGO-Sound-Fix#5]
Hi @patrikzudel,

The program sometimes stuck in tray after exiting csgo.
Right click on the tray icon will not respond.
Need to use task manager to end process.

I havent dig into the code yet, but think it is something within this block:
https://github.com/patrikzudel/PatrikZeros-CSGO-Sound-Fix/blob/main/main.py#L88-L98

As of now I have no video recording yet.
If I somehow get it happen again will see if I can record the issue.

Thanks.

**Comment by patrikzudel** [comment]
Hey! I am not sure what you mean by `The program sometimes stuck in tray after exiting csgo.
`
It is not supposed to turn off after you shut down CS. Does it not turn off when you right click the systray icon and `Quit` ?
