### ISSUE TITLE
set autostart not possible

### ISSUE THREAD

**Issue by moxbo** [patrikzudel/PatrikZeros-CSGO-Sound-Fix#6]
C:\Users\mO\Documents\PatriZero-CSGO-Hearing-Protection>"Start with windows.bat"
Have you put the folder somewhere where you will not delete it (C:/ or Documents) (Y/[N])?Y
C:\Users\mO\AppData\Local\Temp\24049-1466-13614-1174.vbs(6, 1) WshShortcut.Save: Die Verknüpfung "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PatrikZeros CSGO Sound Fix.lnk" wurde nicht gespeichert.

**Comment by patrikzudel** [comment]
As I don't know german I can't really help you here :/ 
The manual way to put something to autostart is as follows

1.  Press Win + R
2.  Write `shell:startup` and press enter
3. It will open a folder, create a shortcut of the `PatrikZeros CSGO Sound Fix.exe` and place it in that folder
4. Done!

**Comment by moxbo** [comment]
The workaround works. Unfortunately the .bat file did not work
