### ISSUE TITLE
New feature needed

### ISSUE THREAD

**Issue by Terman-thr** [patrikzudel/PatrikZeros-CSGO-Sound-Fix#8]
This program is excellent. Now I can play CSGO much more comfortably than before. I am a player from China. Many players here are also very interested in this project(avoid being deaf at Dust2 A long :) ). **Many players also hope this program can reduce the sound of being headshot, which is also very loud.** And another thing is that many people are still worried about being VAC although it has almost been proved VAC safe. I sincerely hope this project can be verified by Faceit and Valve as soon as possible. **Very thankful for your work for the CSGO community!!!**

**Comment by Calinou** [comment]
According to the [README](https://github.com/patrikzudel/PatrikZeros-CSGO-Sound-Fix#readme), it's already Faceit verified.

Also, dink sound volume reduction is already on the list: https://github.com/patrikzudel/PatrikZeros-CSGO-Sound-Fix#-to-be-added

**Comment by patrikzudel** [comment]
Yep, good response from Calinou. Version 1.1 is verified by Faceit and headshot volume reduction is in the To-do.
Thank you for your kind words!
